#!/usr/bin/env node
/** Build a product-specific component gallery: shadcn SaaS or custom marketing sources. */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import * as studio from "./studio.js";
import * as theme from "./theme.js";
import * as designDocument from "./design_document.js";
import * as languageModule from "./language.js";
import * as projectModule from "./project.js";
import { product_context, assert_same_product, validate_custom_coverage } from "./product.js";
import { build_marketing } from "./marketing.js";

const read = studio.read;
const write = studio.write;
const digest = studio.digest;
const save = studio.save;
const validate = theme.validate;
const css = theme.css;
const contrast = theme.contrast;
const visual_contract = theme.visual_contract ?? theme.visualContract;
const component_css = theme.component_css ?? theme.componentCss;
const audit_visual_css = theme.audit_visual_css ?? theme.auditVisualCss;
const document = designDocument.document;
const translated_copy = languageModule.translated_copy ?? languageModule.translatedCopy;
const resolve_project = projectModule.resolve_project ?? projectModule.resolveProject;
const find_web_project = projectModule.find_web_project ?? projectModule.findWebProject;

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
export const ASSETS = path.resolve(SCRIPT_DIR, "../assets");
export const UPSTREAM_BASE = "base";
export const UPSTREAM_COMMIT = "a87a63b2ca25143d26c8bd0903e4e9bc77b3f824";
export const UPSTREAM_ID = `base-ui-source-${UPSTREAM_COMMIT}`;
export const REPOSITORY = "https://github.com/shadcn-ui/ui";
export const RAW_ROOT = `https://raw.githubusercontent.com/shadcn-ui/ui/${UPSTREAM_COMMIT}/apps/v4/`;
export const INDEX_URL = `${RAW_ROOT}public/r/index.json`;
export const SOURCE_ROOT = `${RAW_ROOT}registry/bases/base/`;
export const TEMP_NAMESPACE = path.join(".tmp", "grilling-design-system");
export const MARKER = path.join(TEMP_NAMESPACE, "standalone-owner");
export const CORE = ["button","card","badge","input","label","checkbox","switch","tabs","dialog","progress","avatar","select","slider","textarea","tooltip","sonner"];
export const COMPONENT_CATEGORIES = {
  button:"Actions","button-group":"Actions",toggle:"Actions","toggle-group":"Actions",
  input:"Inputs","input-group":"Inputs","input-otp":"Inputs",textarea:"Inputs",checkbox:"Inputs",
  "radio-group":"Inputs",select:"Inputs","native-select":"Inputs",switch:"Inputs",slider:"Inputs",form:"Inputs",field:"Inputs",label:"Inputs",
  breadcrumb:"Navigation",menubar:"Navigation","navigation-menu":"Navigation",pagination:"Navigation",tabs:"Navigation",sidebar:"Navigation",command:"Navigation",
  "alert-dialog":"Overlays","context-menu":"Overlays",dialog:"Overlays",drawer:"Overlays","dropdown-menu":"Overlays","hover-card":"Overlays",popover:"Overlays",sheet:"Overlays",tooltip:"Overlays",
  alert:"Feedback",empty:"Feedback",progress:"Feedback",skeleton:"Feedback",sonner:"Feedback",spinner:"Feedback",
  "aspect-ratio":"Data display",attachment:"Data display",avatar:"Data display",badge:"Data display",bubble:"Messaging",marker:"Messaging",message:"Messaging","message-scroller":"Messaging",
  card:"Data display",chart:"Data display",item:"Data display",table:"Data display",calendar:"Data display",accordion:"Layout",carousel:"Layout",collapsible:"Layout",resizable:"Layout","scroll-area":"Layout",separator:"Layout",direction:"Utilities",kbd:"Utilities",
};
export const SUPPLEMENTAL_PREVIEWS = { direction:"DirectionDemo",attachment:"AttachmentDemo",bubble:"BubbleDemo",marker:"MarkerDemo",message:"MessageDemo","message-scroller":"MessageScrollerDemo" };
export const GLOBAL_COMPONENT_HOSTS = {
  sonner:{import:'import { Toaster } from "@/components/ui/sonner";',render:"<Toaster />"},
  toast:{import:'import { Toaster as BaseToaster } from "@/components/ui/toast";',render:"<BaseToaster />"},
};
export const MAX_VISUAL_EXAMPLES = 8;
export const INTEGRATED_PREVIEW_MARKER = "GRILLING_INTEGRATED_PREVIEW_PLACEHOLDER";
export const DOCS_ONLY_PATHS = new Set(["src/IntegratedPreview.tsx"]);
export const DOCS_ONLY_COMPONENT_NAMES = new Set(["integrated-preview"]);
export const VISUAL_VARIANTS = {
  button:["default","secondary","destructive","outline","ghost","link","with-icon","loading"], badge:["default","secondary","destructive","outline"],
  input:["disabled","file","with-button","with-label","with-text"],textarea:["disabled","with-button","with-label","with-text"],
  "input-otp":["pattern","separator","controlled"],toggle:["default","outline","disabled","size"],"toggle-group":["default","outline","disabled","size"],
  spinner:["default","button","badge","input-group"],kbd:["default","group","button"],alert:["default","destructive"],checkbox:["default","disabled"],dialog:["close-button"],select:["scrollable"],
};
export const PLACEHOLDER_IMAGE_HOSTS = new Set(["dummyimage.com","fakeimg.pl","loremflickr.com","placebear.com","placekitten.com","picsum.photos","pravatar.cc","placehold.co","placehold.it","placehold.jp","placeholder.com","via.placeholder.com"]);
export const DEMO_PHOTO_HOSTS = new Set(["images.unsplash.com","source.unsplash.com"]);
export const REMOTE_URL = /https?:\/\/[^\s"'`<>}]+/g;

const exists = value => fs.existsSync(value);
const isFile = value => { try { return fs.statSync(value).isFile(); } catch { return false; } };
const isDir = value => { try { return fs.statSync(value).isDirectory(); } catch { return false; } };
const textRead = value => fs.readFileSync(value, "utf8");
const textWrite = (value, content) => { fs.mkdirSync(path.dirname(value), {recursive:true}); fs.writeFileSync(value, content); };
const copy = (source, target) => { fs.mkdirSync(path.dirname(target), {recursive:true}); fs.copyFileSync(source,target); };
const sleep = milliseconds => new Promise(resolve => setTimeout(resolve,milliseconds));
const jsonDump = (value, pretty=false) => JSON.stringify(value,null,pretty?2:undefined);
const removePrefix = (value,prefix) => value.startsWith(prefix)?value.slice(prefix.length):value;
const removeSuffix = (value,suffix) => value.endsWith(suffix)?value.slice(0,-suffix.length):value;
const relativeInside = (candidate,root) => { const rel=path.relative(path.resolve(root),path.resolve(candidate)); return rel==="" || (!rel.startsWith(`..${path.sep}`) && rel!==".." && !path.isAbsolute(rel)); };
const walk = root => { if(!isDir(root)) return []; const out=[]; for(const entry of fs.readdirSync(root,{withFileTypes:true})){ const value=path.join(root,entry.name); if(entry.isDirectory()) out.push(...walk(value)); else out.push(value); } return out; };
const utcDate = () => new Date().toISOString().slice(0,10);
const utcTimestamp = () => new Date().toISOString().replace(/\.\d{3}Z$/,"Z");
const htmlEscape = value => String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;");

export function component_title(name){ const special={kbd:"KBD","input-otp":"Input OTP"}; return special[name] ?? name.split("-").map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(" "); }

export function main_source(tokens,component_names,has_theme_overrides=false){
  const imports=['import React from "react";','import { createRoot } from "react-dom/client";','import App from "./App";','import "./index.css";'];
  const hosts=[];
  for(const [name,host] of Object.entries(GLOBAL_COMPONENT_HOSTS)){ if(component_names.includes(name)){imports.push(host.import);hosts.push(host.render);} }
  if(has_theme_overrides) imports.push('import "./theme-overrides.css";');
  let tree="<App />"+hosts.join("");
  if(component_names.includes("tooltip")){ imports.push('import { TooltipProvider } from "@/components/ui/tooltip";'); tree=`<TooltipProvider>${tree}</TooltipProvider>`; }
  imports.push(`document.documentElement.classList.add(${jsonDump(tokens.mode)});`,`createRoot(document.getElementById("root")!).render(<React.StrictMode>${tree}</React.StrictMode>);`);
  return imports.join("\n")+"\n";
}

export function examples_by_component(names,available){
  const result=Object.fromEntries(names.map(name=>[name,[]]));
  const candidates=Object.values(available).filter(item=>item.type==="registry:example").map(item=>item.name);
  for(const example of candidates){ const owners=names.filter(name=>example===`${name}-demo`||example===`${name}-example`||example.startsWith(`${name}-`)); if(!owners.length) continue; const owner=owners.reduce((a,b)=>a.length>=b.length?a:b); const suffix=removePrefix(example,`${owner}-`); if(["demo","example",...(VISUAL_VARIANTS[owner]??[])].includes(suffix)) result[owner].push(example); }
  for(const [name,examples] of Object.entries(result)){ examples.sort((a,b)=>{const ak=![`${name}-demo`,`${name}-example`].includes(a),bk=![`${name}-demo`,`${name}-example`].includes(b); return Number(ak)-Number(bk)||a.localeCompare(b);}); result[name]=name in SUPPLEMENTAL_PREVIEWS?[]:examples.slice(0,MAX_VISUAL_EXAMPLES); }
  return result;
}

export function load_custom_components(output){
  const manifest=path.join(output,"custom-components.json"); if(!exists(manifest)) return [];
  const data=read(manifest); if(!data||typeof data!=="object"||Array.isArray(data)||!Array.isArray(data.components)) throw new Error("custom-components.json must contain a components array");
  const result=[],seen=new Set(),root=path.resolve(output);
  for(const entry of data.components){
    if(!entry||typeof entry!=="object"||Array.isArray(entry)) throw new Error("Each custom component must be an object");
    for(const key of ["name","title","description","files","preview"]) if(!entry[key]) throw new Error(`Custom component is missing ${key}`);
    const name=entry.name; if(typeof name!=="string"||! /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name)) throw new Error(`Custom component name must use kebab-case: ${name}`);
    if(seen.has(name)) throw new Error(`Duplicate custom component ${name}`);
    if(DOCS_ONLY_COMPONENT_NAMES.has(name)) throw new Error(`${name} is reserved for the docs-only gallery composition and cannot be a custom component`);
    if(Object.hasOwn(entry,"category")) throw new Error(`Custom components use the fixed Custom components category: ${name}`);
    seen.add(name); if(!Array.isArray(entry.files)||!entry.files.length) throw new Error(`Custom component files must be a non-empty array: ${name}`);
    const preview=entry.preview; if(!preview||typeof preview!=="object"||Array.isArray(preview)||!preview.path) throw new Error(`Custom component preview requires path: ${name}`);
    const normalized={...entry,export:preview.export??"default",dependencies:entry.dependencies??[],registryDependencies:entry.registryDependencies??[]};
    for(const pathText of [...entry.files,preview.path]){ const target=path.resolve(output,pathText); if(typeof pathText!=="string"||!pathText.startsWith("src/components/custom/")) throw new Error(`Custom component files must stay in src/components/custom/: ${pathText}`); if(!relativeInside(target,root)||!isFile(target)) throw new Error(`Missing custom component file: ${pathText}`); }
    if(normalized.export!=="default"&&!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(normalized.export)) throw new Error(`Invalid custom preview export: ${normalized.export}`);
    if(![entry.title,entry.description].every(value=>typeof value==="string"&&value)) throw new Error(`Custom component title and description must be strings: ${name}`);
    if(![...normalized.dependencies,...normalized.registryDependencies].every(value=>typeof value==="string"&&value)) throw new Error(`Custom component dependencies must be strings: ${name}`); result.push(normalized);
  } return result;
}

async function requestText(url){ const response=await fetch(url,{headers:{"User-Agent":"Grilling/1.0"},signal:AbortSignal.timeout(45000)}); if(!response.ok) throw new Error(`HTTP ${response.status} ${response.statusText}`); return response.text(); }
export async function fetch_item(name,cache){
  const target=path.join(cache,UPSTREAM_ID,`${name}.json`); if(exists(target)) return read(target); fs.mkdirSync(path.dirname(target),{recursive:true}); let error;
  for(let attempt=0;attempt<3;attempt++){ try { let data; if(name==="registry"){ const index=JSON.parse(await requestText(INDEX_URL)); const ui=index.filter(item=>item.type==="registry:ui"); const examples=ui.filter(item=>item.files?.length&&item.name!=="direction").map(item=>({name:`${item.name}-example`,type:"registry:example",registryDependencies:[item.name,"example"],files:[{path:`registry/bases/base/examples/${item.name}-example.tsx`,type:"registry:example"}]})); data={name:"shadcn/ui Base UI source",homepage:"https://ui.shadcn.com",source:SOURCE_ROOT,items:[...ui,...examples]}; } else {
      const registry=await fetch_item("registry",cache); let metadata=registry.items.find(item=>item.name===name); const special={utils:["lib/utils.ts","registry:lib",["cn"]],example:["components/example.tsx","registry:component",["cn"]],"use-mobile":["hooks/use-mobile.ts","registry:hook",[]]};
      if(special[name]){const [rel,type,deps]=special[name];metadata={name,type,dependencies:deps,files:[{path:`registry/bases/base/${rel}`,type}]};} if(!metadata||!metadata.files?.length) throw new Error(`Base UI source item has no files: ${name}`);
      const files=[]; for(const file of metadata.files){const source=file.path,prefix="registry/bases/base/",rel=source.startsWith(prefix)?source.slice(prefix.length):source;files.push({...file,path:prefix+rel,content:await requestText(SOURCE_ROOT+rel)});} data={...metadata,files}; }
      write(target,data); return data; } catch(caught){ error=caught; await sleep((attempt+1)*1000); } }
  let hint=""; const proxy=process.env.HTTPS_PROXY??process.env.https_proxy; if(proxy&&String(error).includes("CERTIFICATE_VERIFY_FAILED")) hint=`. A system proxy is active (${proxy}); if it intercepts TLS, retry with no_proxy="*"`; throw new Error(`Cannot fetch official shadcn Base UI source item ${name}: ${error}${hint}`);
}
export { fetch_item as fetch };

export function filename(source){ const prefix="registry/bases/base/"; if(!source.startsWith(prefix)) throw new Error(`Unexpected upstream path ${source}`); const rel=source.slice(prefix.length); if(rel.startsWith("ui/")) return `src/components/${rel}`; if(["examples/","blocks/","internal/","components/","hooks/","lib/"].some(value=>rel.startsWith(value))) return `src/${rel}`; throw new Error(`Unsupported upstream file ${source}`); }

export function _image_dimensions(url,tag=""){
  const attribute=name=>{const match=tag.match(new RegExp(`\\b${name}\\s*=\\s*(?:[\"'](\\d+)[\"']|\\{\\s*(\\d+)\\s*\\}|(\\d+))`)); return match?Number(match.slice(1).find(Boolean)):null;}; let width=attribute("width"),height=attribute("height"); let parsed; try{parsed=new URL(url);}catch{return [Math.max(1,width||600),Math.max(1,height||400)];}
  const queryNumber=(...names)=>{for(const name of names){const value=parsed.searchParams.get(name);if(value&&/^\d+$/.test(value)&&Number(value)>0)return Number(value);}return null;}; let sourceWidth=queryNumber("w","width"),sourceHeight=queryNumber("h","height"); const size=parsed.pathname.match(/(?<!\d)(\d{1,5})x(\d{1,5})(?!\d)/i); if(size){sourceWidth=Number(size[1]);sourceHeight=Number(size[2]);}
  const host=parsed.hostname.toLowerCase().replace(/^www\./,""); if(["loremflickr.com","placebear.com","placekitten.com","picsum.photos"].includes(host)){const found=parsed.pathname.match(/\/(?:id\/\d+\/)?(\d{1,5})\/(\d{1,5})(?:\/|$)/);if(found){sourceWidth=Number(found[1]);sourceHeight=Number(found[2]);}} width=width||sourceWidth;height=height||sourceHeight; let ratio=null; if(tag.trimStart().startsWith("<AvatarImage")||/\baspect-square\b/.test(tag))ratio=1;else if(/\baspect-video\b/.test(tag))ratio=16/9;else{const match=tag.match(/\baspect-\[(\d+(?:\.\d+)?)\/(\d+(?:\.\d+)?)\]/);if(match&&Number(match[2]))ratio=Number(match[1])/Number(match[2]);}
  if(ratio&&!width&&!height){width=600;height=Math.round(600/ratio);}else if(width&&!height)height=Math.round(width/(ratio||1.5));else if(height&&!width)width=Math.round(height*(ratio||1.5));return [Math.max(1,width||600),Math.max(1,height||400)];
}
export function _placeholder_kind(url,include_demo_photos=true){let host;try{host=new URL(url).hostname.toLowerCase().replace(/^www\./,"");}catch{return null;}if(host==="dummyimage.com")return "dummyimage";if(PLACEHOLDER_IMAGE_HOSTS.has(host))return "placeholder";if(include_demo_photos&&DEMO_PHOTO_HOSTS.has(host))return "demo-photo";return null;}
export function normalize_placeholder_images(content,include_demo_photos=true,include_remote_images=false){
  const normalize=(url,tag="",allowRemote=false)=>{if(!_placeholder_kind(url,include_demo_photos)&&!allowRemote)return url;const [width,height]=_image_dimensions(url,tag);return `https://dummyimage.com/${width}x${height}/000/fff`;};
  content=content.replace(/<(?:img|Image|AvatarImage)\b[^>]*>/gs,tag=>tag.replace(REMOTE_URL,url=>normalize(url,tag,include_remote_images))); return content.replace(REMOTE_URL,url=>normalize(url));
}
export function remote_example_image_urls(content){const result=new Set();for(const tag of content.match(/<(?:img|Image|AvatarImage)\b[^>]*>/gs)??[]){for(const url of tag.match(REMOTE_URL)??[])if(_placeholder_kind(url)!=="dummyimage")result.add(url);}return [...result].sort();}
export function nonstandard_placeholder_urls(content,include_demo_photos=true){return [...new Set((content.match(REMOTE_URL)??[]).filter(url=>{const kind=_placeholder_kind(url,include_demo_photos);return kind!==null&&kind!=="dummyimage";}))].sort();}
export function normalize_generated_sources(output){const root=path.join(output,"src");if(!exists(root))return;for(const target of walk(root)){if(![".tsx",".jsx",".ts",".js",".html"].includes(path.extname(target)))continue;const generatedExample=relativeInside(target,path.join(root,"examples"))||relativeInside(target,path.join(root,"blocks"));const content=normalize_placeholder_images(textRead(target),generatedExample,generatedExample);const escaped=nonstandard_placeholder_urls(content,generatedExample),escapedImages=generatedExample?remote_example_image_urls(content):[];if(escaped.length)throw new Error(`Nonstandard placeholder images remain in ${target}: ${escaped.join(", ")}`);if(escapedImages.length)throw new Error(`Remote example images remain in ${target}: ${escapedImages.join(", ")}`);textWrite(target,content);}}

export function transform(source,generated_example=false){
  let content=source.replaceAll("@/registry/bases/base/ui/","@/components/ui/").replaceAll("@/registry/bases/base/","@/").replaceAll('from "next-themes"','from "@/lib/theme-mode"').replaceAll('from "next/image"','from "@/lib/next-image"').replaceAll('from "next/link"','from "@/lib/next-link"').replaceAll('from "@tabler/icons-react"','from "@/lib/tabler-icons"');
  if(content.includes("function ScrollArea(")){const without=content.replace('import * as React from "react"\n',"");if(!without.includes("React."))content=without;}
  if(content.includes("function DropdownMenuContent("))content=content.replace('<MenuPrimitive.Positioner\n        className="isolate z-50 outline-none"','<MenuPrimitive.Positioner\n        data-slot="dropdown-menu-positioner"\n        className="cn-dropdown-menu-positioner isolate z-50 outline-none"');
  if(content.includes("function SelectTrigger(")&&!content.includes("cn-select-trigger-icon-glyph")){let count=0;content=content.replace(/<SelectPrimitive\.Icon\s+render=\{\s*<ChevronDownIcon className="cn-select-trigger-icon pointer-events-none" \/>\s*\}\s*\/>/g,()=>{count++;return `<SelectPrimitive.Icon
        render={
          <span className="cn-select-trigger-icon" aria-hidden="true">
            <ChevronDownIcon className="cn-select-trigger-icon-glyph pointer-events-none" />
          </span>
        }
      />`;});content=content.replace(/<SelectPrimitive\.Icon\s+render=\{\s*<IconPlaceholder\b(?=[^>]*\blucide=["']ChevronDownIcon["'])(?=[^>]*\bclassName=["']cn-select-trigger-icon pointer-events-none["'])[^>]*\/>\s*\}\s*\/>/gs,()=>{count++;return `<SelectPrimitive.Icon
        render={
          <span className="cn-select-trigger-icon" aria-hidden="true">
            <ChevronDownIcon className="cn-select-trigger-icon-glyph pointer-events-none" />
          </span>
        }
      />`;});if(count!==1)throw new Error("SelectTrigger disclosure icon markup changed upstream");}
  if(content.includes("function NavigationMenuTrigger(")&&!content.includes("cn-navigation-menu-trigger-icon-glyph")){let count=0;content=content.replace(/<ChevronDownIcon className="cn-navigation-menu-trigger-icon"\s+aria-hidden="true" \/>/g,()=>{count++;return `<span className="cn-navigation-menu-trigger-icon" aria-hidden="true">
        <ChevronDownIcon className="cn-navigation-menu-trigger-icon-glyph" />
      </span>`;});content=content.replace(/<IconPlaceholder\b(?=[^>]*\blucide=["']ChevronDownIcon["'])(?=[^>]*\bclassName=["']cn-navigation-menu-trigger-icon["'])[^>]*\/>/gs,()=>{count++;return `<span className="cn-navigation-menu-trigger-icon" aria-hidden="true">
        <ChevronDownIcon className="cn-navigation-menu-trigger-icon-glyph" />
      </span>`;});if(count!==1)throw new Error("NavigationMenuTrigger disclosure icon markup changed upstream");}
  content=content.replace(/(?<![A-Za-z0-9_-])style-(?:vega|nova|maia|lyra|mira|luma|sera|rhea):[^\s"']+/g,"");
  const icons=content.includes("<ChevronDownIcon")?["ChevronDownIcon"]:[];content=content.replace(/<IconPlaceholder\b(.*?)\/>/gs,(_match,attrs)=>{const icon=attrs.match(/\blucide=["']([^"']+)["']/);if(!icon)throw new Error("IconPlaceholder is missing a Lucide mapping");const name=icon[1];if(!icons.includes(name))icons.push(name);attrs=attrs.replace(/\s+(?:lucide|tabler|hugeicons|phosphor|remixicon)=["'][^"']+["']/g,"").trim();return `<${name}${attrs?` ${attrs}`:""} />`;});
  content=content.replace(/import\s*\{\s*IconPlaceholder\s*\}\s*from\s*["'][^"']*icon-placeholder["']\s*;?\n?/g,"");
  if(icons.length){const imported=content.match(/import\s*\{([^}]*)\}\s*from\s*["']lucide-react["']\s*;?/s);if(imported){const existing=imported[1].split(",").map(value=>value.trim()).filter(Boolean),aliases=new Set(existing.map(value=>value.split(" as " ).at(-1)));const merged=[...existing,...icons.filter(name=>!aliases.has(name))];content=content.slice(0,imported.index)+`import { ${merged.join(", ")} } from "lucide-react"`+content.slice(imported.index+imported[0].length);}else{const directive=content.match(/^(["']use client["'];?\s*)/);const offset=directive?directive[0].length:0;content=content.slice(0,offset)+`\nimport { ${icons.join(", ")} } from "lucide-react"\n`+content.slice(offset);}}
  content=normalize_placeholder_images(content,true,generated_example);const escaped=nonstandard_placeholder_urls(content);if(escaped.length)throw new Error(`Nonstandard placeholder images remain: ${escaped.join(", ")}`);const escapedImages=generated_example?remote_example_image_urls(content):[];if(escapedImages.length)throw new Error(`Remote example images remain: ${escapedImages.join(", ")}`);return content;
}

export function theme_example(name,source){
  let content=source;const replacements={
    "checkbox-example":{"dark:has-[[aria-checked=true]]:border-blue-900":"","dark:has-[[aria-checked=true]]:bg-blue-950":"","dark:data-[state=checked]:border-blue-700":"","dark:data-[state=checked]:bg-blue-700":"","has-[[aria-checked=true]]:border-blue-600":"has-[[aria-checked=true]]:border-primary","has-[[aria-checked=true]]:bg-blue-50":"has-[[aria-checked=true]]:bg-primary/5","data-[state=checked]:border-blue-600":"data-[state=checked]:border-primary","data-[state=checked]:bg-blue-600":"data-[state=checked]:bg-primary","data-[state=checked]:text-white":"data-[state=checked]:text-primary-foreground"},
    "badge-example":{"dark:bg-blue-600":"","bg-blue-500 text-white":"bg-primary text-primary-foreground"},"toggle-example":{"fill-blue-500":"fill-primary","stroke-blue-500":"stroke-primary"},
  };for(const [from,to] of Object.entries(replacements[name]??{}))content=content.replaceAll(from,to);
  if(name==="example")content=content.replaceAll("min-h-screen","min-h-0").replaceAll("md:grid-cols-2","");
  if(name==="sidebar-example")content=content.replace("<DropdownMenuContent>",'<DropdownMenuContent className="cn-sidebar-dropdown-content">');
  if(["input-otp","input-otp-example"].includes(name))content=content.replaceAll('<RefreshCwIcon data-icon="inline-start" />','<RefreshCwIcon data-icon="inline-start" className="size-3.5" />');
  if(name==="calendar-example"&&content.includes("function CalendarCustomDays()")){const from='className="[--cell-size:--spacing(10)] md:[--cell-size:--spacing(12)]"',to='className="cn-calendar-custom-days [--cell-size:--spacing(12)]"';if(!content.includes(from)&&!content.includes(to))throw new Error("CalendarCustomDays cell-size markup changed upstream");content=content.replaceAll(from,to);}
  if(["progress","progress-example"].includes(name)&&content.includes("function FileUploadList()")){content=content.replaceAll('className="inline-block truncate"','className="min-w-0 inline-block truncate"').replace(/<ItemContent>\s*<Progress value=\{file\.progress\} className="w-32" \/>\s*<\/ItemContent>/g,'<ItemContent className="order-last !flex-[0_0_100%] pl-8">\n              <Progress value={file.progress} className="w-full" />\n            </ItemContent>').replaceAll('className="w-16 justify-end"','className="w-16 shrink-0 justify-end"');}
  if(["collapsible","collapsible-example"].includes(name))content=content.replaceAll(" hover:bg-accent hover:text-accent-foreground","").replaceAll("group-data-[state=open]:rotate-90","group-data-[panel-open]:rotate-90");return content;
}

export function dependencies(items){const result={};for(const item of items)for(const dep of [...(item.dependencies??[]),...(item.devDependencies??[])]){const match=dep.match(/^(@[^/]+\/[^@]+|[^@]+)(?:@(.+))?$/);if(!match)throw new Error(`Unsupported dependency ${dep}`);result[match[1]]=match[2]??"latest";}return result;}
export function preserve_previous_dependencies(current,previous){for(const [name,version] of Object.entries(previous)){const legacy=name==="radix-ui"||name.startsWith("@radix-ui/");if(Object.hasOwn(current,name)||!legacy)current[name]=version;}return current;}
export function source_digest(items){const sources={};for(const item of Object.values(items))for(const file of item.files??[])if(file.content!=null)sources[file.path]=file.content;return digest(sources);}
export function tool_version(command){try{return String(execFileSync(command[0],command.slice(1),{encoding:"utf8",stdio:["ignore","pipe","pipe"]})).trim().split(/\r?\n/)[0];}catch{return "unavailable";}}
export async function collect(names,cache){const items={};let pending=new Set([...names,"utils"]);while(pending.size){const batch=await Promise.all([...pending].sort().map(name=>fetch_item(name,cache)));pending=new Set();for(const item of batch){items[item.name]=item;for(const dep of item.registryDependencies??[]){if(dep.startsWith("http")||dep.startsWith("@"))throw new Error(`Unexpected registry dependency ${dep}`);if(!Object.hasOwn(items,dep))pending.add(dep);}}for(const key of Object.keys(items))pending.delete(key);}return items;}
export function local_registry_imports(item){const result=new Set(),prefix="@/registry/bases/base/",regex=new RegExp(`from\\s*[\"']${prefix.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}(ui|hooks|lib|components)/([^\"']+)[\"']`,"g");for(const file of item.files??[]){for(const match of (file.content??"").matchAll(regex))if(match[1]==="ui")result.add(match[2].split("/").at(-1));}return result;}
export async function collect_source_imports(items,cache){let pending=new Set([...Object.values(items).flatMap(item=>[...local_registry_imports(item)])].filter(name=>!Object.hasOwn(items,name)));while(pending.size){const extra=await collect([...pending],cache);Object.assign(items,extra);pending=new Set([...Object.values(extra).flatMap(item=>[...local_registry_imports(item)])].filter(name=>!Object.hasOwn(items,name)));}return items;}

export function scaffold(output,lang,title,style,custom=false){fs.mkdirSync(output,{recursive:true});textWrite(path.join(output,MARKER),"Generated by grilling-design-system library.js\n");fs.mkdirSync(path.join(output,"src"),{recursive:true});textWrite(path.join(output,"index.html"),`<!doctype html><html lang="${htmlEscape(lang)}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${htmlEscape(title)}</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>`);textWrite(path.join(output,"vite.config.ts"),'import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\nimport tailwindcss from "@tailwindcss/vite";\nimport { fileURLToPath, URL } from "node:url";\nexport default defineConfig({base:"./",plugins:[react(),tailwindcss()],resolve:{alias:{"@":fileURLToPath(new URL("./src",import.meta.url))}}});\n');write(path.join(output,"tsconfig.json"),{compilerOptions:{target:"ES2022",lib:["ES2022","DOM","DOM.Iterable"],module:"ESNext",moduleResolution:"Bundler",jsx:"react-jsx",strict:true,skipLibCheck:true,allowSyntheticDefaultImports:true,esModuleInterop:true,resolveJsonModule:true,noEmit:true,baseUrl:".",paths:{"@/*":["./src/*"]}},include:["src","vite.config.ts"]});if(!custom)write(path.join(output,"components.json"),{$schema:"https://ui.shadcn.com/schema.json",style,rsc:false,tsx:true,tailwind:{config:"",css:"src/index.css",baseColor:"neutral",cssVariables:true,prefix:""},iconLibrary:"lucide",aliases:{components:"@/components",utils:"@/lib/utils",ui:"@/components/ui",lib:"@/lib",hooks:"@/hooks"}});}

export function prepare_integrated_preview(output,require_authored=false,custom=false){const preview=path.join(output,"src/IntegratedPreview.tsx");if(!exists(preview))copy(path.join(ASSETS,custom?"CustomIntegratedPreview.tsx":"IntegratedPreview.tsx"),preview);if(!require_authored)return;const previewSource=textRead(preview);if(previewSource.includes(INTEGRATED_PREVIEW_MARKER))throw new Error("Replace src/IntegratedPreview.tsx with the confirmed Key Visual and remove its placeholder marker before delivery");if(!/from\s+["']@\/components\//.test(previewSource))throw new Error("The confirmed Key Visual must import and render delivered components from @/components/");const app=path.join(output,"src/App.tsx"),source=exists(app)?textRead(app):"",previewPosition=source.indexOf('data-slot="integrated-preview"'),directoryPosition=source.indexOf('className="component-directory"');if(previewPosition<0||directoryPosition<0||previewPosition>directoryPosition)throw new Error('The component overview must render data-slot="integrated-preview" before the component directory');}

export function registry(output,items,t,packageData,custom_components){
  const artifactName=t.slug,themeFile=`src/${artifactName}.css`,deliveredPaths=new Set(custom_components.flatMap(entry=>entry.files)),previewPaths=new Set(custom_components.filter(entry=>!deliveredPaths.has(entry.preview.path)).map(entry=>entry.preview.path)),files=[];
  files.push({path:"SHADCN-LICENSE.txt",target:"SHADCN-LICENSE.txt",type:"registry:file",content:textRead(path.join(ASSETS,"SHADCN-LICENSE.txt"))});
  for(const target of walk(path.join(output,"src")).sort()){if(!isFile(target)||![".tsx",".ts",".css",".svg",".json"].includes(path.extname(target)))continue;const rel=path.relative(output,target).split(path.sep).join("/");if(previewPaths.has(rel)||DOCS_ONLY_PATHS.has(rel))continue;if(!["src/components/","src/hooks/","src/lib/","src/assets/"].some(prefix=>rel.startsWith(prefix))&&rel!=="src/theme-overrides.css")continue;const ext=path.extname(target),kind=![".tsx",".ts"].includes(ext)?"registry:file":rel.includes("/ui/")?"registry:ui":rel.includes("/hooks/")?"registry:hook":rel.includes("/lib/")?"registry:lib":"registry:component";files.push({path:rel,type:kind,target:rel,content:textRead(target)});}
  const hooks=visual_contract(Object.values(items).map(item=>item.files??[]));
  let generatedTheme=css(t,true,hooks.hooks).replace('@import "tailwindcss";\n',"").replace('@import "tw-animate-css";\n',"").replace('@import "shadcn/tailwind.css";\n',"");
  if(exists(path.join(output,"src/theme-overrides.css"))){
    // Keep imports valid while matching main.tsx: defaults first, authored rules last.
    const baseFile=`src/${artifactName}.base.css`;
    textWrite(path.join(output,baseFile),generatedTheme);
    files.push({path:baseFile,target:baseFile,type:"registry:file",content:generatedTheme});
    generatedTheme=`@import "./${artifactName}.base.css";\n@import "./theme-overrides.css";\n`;
  }
  textWrite(path.join(output,themeFile),generatedTheme);files.push({path:themeFile,target:themeFile,type:"registry:file",content:generatedTheme});
  const deps=Object.entries(packageData.dependencies).filter(([name])=>!["react","react-dom"].includes(name)).map(([name,version])=>`${name}@${version}`);const item={$schema:"https://ui.shadcn.com/schema/registry-item.json",name:"all",type:"registry:block",title:t.name,description:"Themed shadcn collection with custom components. See DESIGN.md for approval status.",dependencies:deps,files,css:{[`@import "./${artifactName}.css"`]:{},'@import "tw-animate-css"':{},'@import "shadcn/tailwind.css"':{}}},catalog=[item];
  for(const entry of custom_components){const customFiles=entry.files.map(rel=>{const target=path.join(output,rel);return {path:rel,target:rel,type:[".tsx",".ts"].includes(path.extname(target))?"registry:component":"registry:file",content:textRead(target)};}),customItem={$schema:"https://ui.shadcn.com/schema/registry-item.json",name:entry.name,type:"registry:component",title:entry.title,description:entry.description,files:customFiles};if(entry.dependencies.length)customItem.dependencies=entry.dependencies;if(entry.registryDependencies.length)customItem.registryDependencies=entry.registryDependencies;write(path.join(output,"public/r",`${entry.name}.json`),customItem);catalog.push(customItem);}
  write(path.join(output,"public/r/all.json"),item);write(path.join(output,"registry.json"),{$schema:"https://ui.shadcn.com/schema/registry.json",name:artifactName,homepage:"https://ui.shadcn.com",items:catalog});
}

export function component_catalog_entries(names,custom_components,labels){const reserved=[...DOCS_ONLY_COMPONENT_NAMES].filter(name=>names.includes(name)||custom_components.some(entry=>entry.name===name));if(reserved.length)throw new Error(`Docs-only component names cannot enter componentEntries: ${reserved.sort().join(", ")}`);return [...names.map(name=>({name,title:component_title(name),category:labels[COMPONENT_CATEGORIES[name]??"Utilities"],description:labels["Visual preview, variants and interaction states for this component."]})),...custom_components.map(entry=>({name:entry.name,title:entry.title,category:labels["Custom components"],description:entry.description}))];}

function run(command,args,cwd){execFileSync(command,args,{cwd,stdio:"inherit"});}
export async function build(args){
  const stateContext=args.session?read(path.join(args.session,"session.json"))?.context:null;
  const supplied=args.context?read(args.context):null;
  const detected=resolve_project(process.cwd(),args.output??supplied?.output??stateContext?.output);
  const storedPath=path.join(detected.output,"design-context.json");
  const stored=isFile(storedPath)?read(storedPath):null;
  const context=product_context({...detected,...(supplied??stateContext??stored??{})});
  if(args.output&&path.resolve(args.output)!==path.resolve(context.output))throw new Error("--output must match the recorded context");
  assert_same_product(stateContext,context);assert_same_product(stored,context);
  const output=path.resolve(context.output),[destinationRoot]=find_web_project(output);let generated=isFile(path.join(output,MARKER));if(!generated&&isFile(path.join(output,"package.json")))generated=["tokens.json","registry.json","shadcn-snapshot.json"].every(rel=>isFile(path.join(output,rel)))||["tokens.json","design-context.json","source-snapshot.json"].every(rel=>isFile(path.join(output,rel)));if(context.taskType==="optimize")throw new Error("Optimize target pages in the host; do not run the standalone scaffold");if(!generated&&(detected.mode==="integrated"||context.mode==="integrated"||destinationRoot))throw new Error("Existing Web project detected. Integrate components using references/project-output.md; this generator creates a standalone Vite application. Use --sources-only to fetch upstream inputs.");
  if(context.productType==="marketing")return build_marketing(args,context);
  const cache=path.resolve(args.cache);fs.mkdirSync(cache,{recursive:true});const state=args.session?read(path.join(args.session,"session.json")):null,lang=args.language??state?.language;if(!lang)throw new Error("Pass --language using the user’s main language");const labels=translated_copy(lang,args.ui_copy?read(args.ui_copy):null,"library-copy.json");let t;if(args.deliver){if(!state||!["approved","delivered"].includes(state.status))throw new Error("Delivery requires explicit approval of the latest preview");t=state.accepted.foundations.tokens;if(digest(t)!==state.approval.tokenHash)throw new Error("Approval is stale");}else{if(!args.tokens)throw new Error("Provide --tokens for a draft");t=read(args.tokens);}validate(t);const failures=contrast(t).filter(result=>!result.passAA);if(failures.length)throw new Error(`Fix failing token contrasts before generating: ${jsonDump(failures)}`);if(args.deliver&&!args.build)throw new Error("Delivery requires --build");
  const upstream=await fetch_item("registry",cache),unavailableUi=upstream.items.filter(item=>item.type==="registry:ui"&&!item.files?.length).map(item=>item.name),names=(args.full||args.deliver?upstream.items.filter(item=>item.type==="registry:ui"&&item.files?.length).map(item=>item.name):[...CORE]),available=Object.fromEntries(upstream.items.map(item=>[item.name,item])),customComponents=load_custom_components(output),customNames=new Set(customComponents.map(entry=>entry.name)),collisions=names.filter(name=>customNames.has(name));if(collisions.length)throw new Error(`Custom component names collide with shadcn components: ${collisions.sort().join(", ")}`);
  validate_custom_coverage(customComponents,context,args.full||args.deliver);
  let demos=[],componentDemos=Object.fromEntries(names.map(name=>[name,[]]));if(args.full||args.deliver){componentDemos=examples_by_component(names,available);if(Object.hasOwn(componentDemos,"chart")&&!componentDemos.chart.length&&available["chart-bar-demo"])componentDemos.chart=["chart-bar-demo"];demos=names.flatMap(name=>componentDemos[name]);}else for(const name of names){const candidate=available[`${name}-example`]?`${name}-example`:available[`${name}-demo`]?`${name}-demo`:name==="chart"?"chart-bar-demo":null;if(candidate){componentDemos[name]=[candidate];demos.push(candidate);}}
  const items=await collect_source_imports(await collect([...names,...demos],cache),cache),previous=exists(path.join(output,"package.json"))?read(path.join(output,"package.json")):{};scaffold(output,lang,t.name,t.slug);write(path.join(output,"design-context.json"),context);textWrite(path.join(output,"src/review-copy.ts"),`export const text: Record<string, string> = ${jsonDump(labels)};\n`);copy(path.join(ASSETS,"SHADCN-LICENSE.txt"),path.join(output,"SHADCN-LICENSE.txt"));if(generated&&exists(path.join(output,"src/components/ui")))fs.rmSync(path.join(output,"src/components/ui"),{recursive:true});if(generated&&exists(path.join(output,"src/examples")))fs.rmSync(path.join(output,"src/examples"),{recursive:true});
  for(const item of Object.values(items))for(const file of item.files??[]){if(!file.content)continue;const target=path.join(output,filename(file.path)),generatedExample=["registry:example","registry:block"].includes(item.type);let content=theme_example(item.name,transform(file.content,generatedExample));if(item.name.startsWith("chart-")&&generatedExample){const palette=new Map();content=content.replace(/color:\s*"(#[0-9a-fA-F]{3,8})"/g,(_match,color)=>{if(!palette.has(color))palette.set(color,palette.size%5+1);return `color: "var(--chart-${palette.get(color)})"`;});}textWrite(target,content);}
  fs.mkdirSync(path.join(output,"src/lib"),{recursive:true});textWrite(path.join(output,"src/lib/next-image.tsx"),'import type { ImgHTMLAttributes } from "react";\nexport default function Image({fill,priority,quality,...props}:ImgHTMLAttributes<HTMLImageElement>&{fill?:boolean;priority?:boolean;quality?:number}){return <img {...props} style={{...(fill?{width:"100%",height:"100%",objectFit:"cover" as const}:{}),...props.style}}/>;}\n');textWrite(path.join(output,"src/lib/next-link.tsx"),'import type { AnchorHTMLAttributes } from "react";\nexport default function Link(props:AnchorHTMLAttributes<HTMLAnchorElement>){return <a {...props}/>;}\n');textWrite(path.join(output,"src/lib/theme-mode.ts"),'import { useEffect, useState } from "react";\nexport function useTheme(){const read=()=>document.documentElement.classList.contains("dark")?"dark":"light";const [theme,setTheme]=useState(read);useEffect(()=>{const observer=new MutationObserver(()=>setTheme(read()));observer.observe(document.documentElement,{attributes:true,attributeFilter:["class"]});return ()=>observer.disconnect()},[]);return {theme};}\n');
  const iconNames=new Set();for(const target of exists(path.join(output,"src/examples"))?fs.readdirSync(path.join(output,"src/examples")).filter(name=>name.endsWith(".tsx")).map(name=>path.join(output,"src/examples",name)):[])for(const block of textRead(target).matchAll(/import\s*\{([^}]+)\}\s*from\s*["']@\/lib\/tabler-icons["']/g))for(const name of block[1].split(",").map(value=>value.trim()).filter(Boolean))iconNames.add(name);const iconMap={IconSearch:"Search",IconArrowUp:"ArrowUp",IconCheck:"Check",IconCopy:"Copy",IconCreditCard:"CreditCard",IconFolderCode:"FolderCode",IconInfoCircle:"Info",IconPlus:"Plus",IconBrandGithub:"Github"};textWrite(path.join(output,"src/lib/tabler-icons.tsx"),`export { ${[...iconNames].sort().map(name=>`${iconMap[name]??"Circle"} as ${name}`).join(", ")} } from "lucide-react";\n`);
  let deps=dependencies(Object.values(items));Object.assign(deps,dependencies(customComponents.map(entry=>({dependencies:entry.dependencies}))));Object.assign(deps,{react:"^19.1.0","react-dom":"^19.1.0","class-variance-authority":"^0.7.1","lucide-react":"^0.468.0",cn:"latest","@base-ui/react":"latest","tw-animate-css":"latest",shadcn:"4.21.0"});deps=preserve_previous_dependencies(deps,previous.dependencies??{});const packageData={name:t.slug,version:"0.1.0",private:true,type:"module",scripts:{dev:"vite --host 127.0.0.1",build:"tsc --noEmit && vite build",preview:"vite preview --host 127.0.0.1",...(previous.scripts??{})},dependencies:deps,devDependencies:{typescript:"^5.8.3",vite:"^6.4.1","@vitejs/plugin-react":"^4.7.0",tailwindcss:"^4.1.0","@tailwindcss/vite":"^4.1.0","@types/react":"^19.1.0","@types/react-dom":"^19.1.0","@types/node":"^22.0.0",...(previous.devDependencies??{})}};write(path.join(output,"package.json"),packageData);write(path.join(output,"tokens.json"),t);
  const contract=visual_contract(Object.values(items).map(item=>item.files??[])),explicitStyles=component_css([]),stylesheet=css(t,true,contract.hooks),audit=audit_visual_css(contract,stylesheet,explicitStyles);if(audit.missingHooks.length)throw new Error(`Generated visual layer is missing semantic hooks: ${audit.missingHooks.join(", ")}`);if(audit.missingStates.length)throw new Error(`Generated visual layer is missing visible Base UI states: ${audit.missingStates.join(", ")}`);if(audit.missingStructures.length)throw new Error(`Generated visual layer is missing critical component structure: ${audit.missingStructures.join(", ")}`);if(audit.unclassifiedHooks.length)throw new Error(`Classify new Base UI semantic hooks before generation: ${audit.unclassifiedHooks.join(", ")}`);textWrite(path.join(output,"src/index.css"),stylesheet);write(path.join(output,"style-provenance.json"),theme.style_provenance(t));textWrite(path.join(output,"src/main.tsx"),main_source(t,names,exists(path.join(output,"src/theme-overrides.css"))));if(!exists(path.join(output,"src/App.tsx")))copy(path.join(ASSETS,"App.tsx"),path.join(output,"src/App.tsx"));if(!exists(path.join(output,"src/gallery.css")))copy(path.join(ASSETS,"gallery.css"),path.join(output,"src/gallery.css"));prepare_integrated_preview(output,args.deliver);normalize_generated_sources(output);
  const demoImports=['import { Suspense, lazy } from "react";','import type { ComponentType, LazyExoticComponent } from "react";','import { text } from "./review-copy";'],previewEntries=Object.fromEntries(names.map(name=>[name,[]]));for(let i=0;i<demos.length;i++){const name=demos[i],item=items[name],sourceFile=(item.files??[]).find(file=>(file.content??"").includes("export default"));if(!sourceFile)continue;const file=removeSuffix(filename(sourceFile.path).slice(4),".tsx");demoImports.push(`const D${i}=lazy(()=>import("./${file}"));`);const componentName=Object.entries(componentDemos).find(([,examples])=>examples.includes(name))?.[0];if(componentName){const suffix=removePrefix(name,`${componentName}-`),title=suffix==="demo"?"Preview":component_title(suffix);previewEntries[componentName].push(`{title:${jsonDump(title)},Preview:D${i}}`);}}
  if(args.full||args.deliver){copy(path.join(ASSETS,"SupplementalGallery.tsx"),path.join(output,"src/SupplementalGallery.tsx"));demoImports.push(`import { ${Object.values(SUPPLEMENTAL_PREVIEWS).join(", ")} } from "./SupplementalGallery";`);for(const [name,exportName] of Object.entries(SUPPLEMENTAL_PREVIEWS))if(names.includes(name)&&!previewEntries[name].length)previewEntries[name].push(`{title:"Preview",Preview:${exportName}}`);}
  for(let index=0;index<customComponents.length;index++){const entry=customComponents[index],importPath=`@/${removeSuffix(removePrefix(entry.preview.path,"src/"),path.extname(entry.preview.path))}`,symbol=`CustomPreview${index}`;demoImports.push(entry.export==="default"?`const ${symbol}=lazy(()=>import(${jsonDump(importPath)}));`:`const ${symbol}=lazy(()=>import(${jsonDump(importPath)}).then(module=>({default:module.${entry.export}})));`);previewEntries[entry.name]=[`{title:"Preview",Preview:${symbol}}`];}
  const entries=component_catalog_entries(names,customComponents,labels);demoImports.push(`export const componentEntries = ${jsonDump(entries)} as const;`);const previewMap=Object.entries(previewEntries).filter(([,values])=>values.length).map(([name,values])=>`${jsonDump(name)}:[${values.join(",")}]`).join(",");demoImports.push("type PreviewEntry={title:string,Preview:ComponentType|LazyExoticComponent<ComponentType>};",`const previews: Record<string, PreviewEntry[]> = {${previewMap}};`,'export function ComponentPreview({entry}:{entry:(typeof componentEntries)[number]}){const examples=previews[entry.name]||[];if(!examples.length)return <p className="demo-empty">{text["Preview unavailable"]}</p>;return <div className="component-previews">{examples.map(({title,Preview})=><section className="visual-example" key={title}><h3>{title}</h3><div className="visual-example-canvas"><Suspense fallback={<p className="demo-empty">{text["Loading…"]}</p>}><Preview/></Suspense></div></section>)}</div>}','export default function FullGallery(){return <div className="gallery-grid">{componentEntries.map(entry=><section className="gallery-item" id={entry.name} key={entry.name}><h3>{entry.title}</h3><ComponentPreview entry={entry}/></section>)}</div>;}');textWrite(path.join(output,"src/FullGallery.tsx"),demoImports.join("\n"));
  const customHashes=Object.fromEntries(customComponents.map(entry=>[entry.name,digest(Object.fromEntries(entry.files.map(rel=>[rel,textRead(path.join(output,rel))])))])),toolchain={node:tool_version(["node","--version"]),npm:tool_version(["npm","--version"]),generatorSha256:crypto.createHash("sha256").update(fs.readFileSync(fileURLToPath(import.meta.url))).digest("hex"),componentStylesSha256:crypto.createHash("sha256").update(fs.readFileSync(path.join(ASSETS,"components.css"))).digest("hex"),themeGeneratorSha256:crypto.createHash("sha256").update(fs.readFileSync(path.join(SCRIPT_DIR,"theme.js"))).digest("hex")},snapshot={repository:REPOSITORY,commit:UPSTREAM_COMMIT,url:SOURCE_ROOT,indexUrl:INDEX_URL,sourceLayer:"shadcn Base UI components",style:"generated from approved tokens",primitive:"Base UI",fetchedAt:utcDate(),indexSha256:digest(upstream),sourceSha256:source_digest(items),toolchain,visualContract:{hookCount:contract.hooks.length,hookHash:digest(contract.hooks),states:Object.keys(contract.requiredStates).sort(),observedStates:contract.observedStates,explicitHookCount:audit.explicitHooks.length,inferredHookCount:audit.inferredHooks.length,structuralHookCount:audit.structuralHooks.length},ui:names,unavailableUi,custom:customComponents.map(entry=>entry.name),customItems:customHashes,demos,items:Object.fromEntries(Object.keys(items).sort().map(name=>[name,digest(items[name])]))};write(path.join(output,"visual-contract.json"),{...contract,...audit,sourceCommit:UPSTREAM_COMMIT});const checks=state?.round?.checks??{};write(path.join(output,"contrast-report.json"),contrast(t));
  if(args.install){run("npm",["install","--no-audit","--no-fund"],output);const lock=read(path.join(output,"package-lock.json"));for(const dep of Object.keys(packageData.dependencies)){const resolved=lock.packages?.[`node_modules/${dep}`]?.version;if(resolved)packageData.dependencies[dep]=resolved;}write(path.join(output,"package.json"),packageData);run("npm",["install","--package-lock-only","--no-audit","--no-fund"],output);snapshot.lockfileSha256=crypto.createHash("sha256").update(fs.readFileSync(path.join(output,"package-lock.json"))).digest("hex");snapshot.resolvedDependencies=packageData.dependencies;}snapshot.deliverySha256=digest(snapshot);write(path.join(output,"shadcn-snapshot.json"),snapshot);const designDoc=document(output,t,state,snapshot,checks,context);registry(output,items,t,packageData,customComponents);if(args.build)run("npm",["run","build"],output);const result={output:String(output),components:names.length+customComponents.length,officialComponents:names.length,customComponents:customComponents.length,tokenHash:digest(t),demos:demos.length,designDocument:String(designDoc)};if(path.resolve(designDoc)!==path.resolve(output,"DESIGN.md"))result.notice="Existing completed DESIGN.md was preserved; merge the refreshed draft into it.";if(args.deliver){state.generated={path:String(output),tokenHash:digest(t),componentCount:names.length+customComponents.length,snapshotHash:snapshot.deliverySha256,snapshotPath:"shadcn-snapshot.json",context,at:utcTimestamp()};save(args.session,state);result.next="Complete DESIGN.md, then run studio.js finish with delivery evidence.";}console.log(JSON.stringify(result,null,2));return result;
}

export function parse_args(argv=process.argv.slice(2)){const args={output:null,cache:path.join(".tmp","grilling-design-system","cache"),tokens:null,session:null,full:false,deliver:false,install:false,build:false,sources_only:false,language:null,ui_copy:null,context:null};const values={"--context":"context","--output":"output","--cache":"cache","--tokens":"tokens","--session":"session","--language":"language","--ui-copy":"ui_copy"},flags={"--full":"full","--deliver":"deliver","--install":"install","--build":"build","--sources-only":"sources_only"};for(let index=0;index<argv.length;index++){const option=argv[index];if(option==="-h"||option==="--help"){console.log("usage: library.js [--context CONTEXT] [--output OUTPUT] [--cache CACHE] [--tokens TOKENS] [--session SESSION] [--full] [--deliver] [--install] [--build] [--sources-only] [--language LANGUAGE] [--ui-copy UI_COPY]\n\nBuild a product-specific component gallery: shadcn SaaS or custom marketing sources.");return null;}if(flags[option])args[flags[option]]=true;else if(values[option]){if(index+1>=argv.length)throw new Error(`argument ${option}: expected one argument`);args[values[option]]=argv[++index];}else throw new Error(`unrecognized argument: ${option}`);}return args;}

export async function main(argv=process.argv.slice(2)){const args=parse_args(argv);if(!args)return;if(args.sources_only){if(args.context&&product_context(read(args.context)).productType==="marketing")throw new Error("Marketing components are authored locally; --sources-only is SaaS-only");if(args.install||args.build||args.deliver)throw new Error("--sources-only cannot install, build, or mark delivery");const cache=path.resolve(args.cache);fs.mkdirSync(cache,{recursive:true});const upstream=await fetch_item("registry",cache),unavailableUi=upstream.items.filter(item=>item.type==="registry:ui"&&!item.files?.length).map(item=>item.name),names=args.full?upstream.items.filter(item=>item.type==="registry:ui"&&item.files?.length).map(item=>item.name):[...CORE],items=await collect_source_imports(await collect(names,cache),cache),contract=visual_contract(Object.values(items).map(item=>item.files??[]));write(path.join(cache,"source-manifest.json"),{repository:REPOSITORY,commit:UPSTREAM_COMMIT,url:SOURCE_ROOT,indexUrl:INDEX_URL,fetchedAt:utcDate(),sha256:digest(upstream),sourceLayer:"shadcn Base UI components",style:"generated from approved tokens",primitive:"Base UI",visualContract:{hookCount:contract.hooks.length,hookHash:digest(contract.hooks),states:Object.keys(contract.requiredStates).sort(),observedStates:contract.observedStates},ui:names,unavailableUi,items:Object.fromEntries(Object.entries(items).map(([name,item])=>[name,digest(item)]))});console.log(JSON.stringify({cache:String(cache),components:names.length,mode:"sources-only"},null,2));return;}return build(args);}

const isMain=process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url);if(isMain)main().catch(error=>{console.error(error?.message??String(error));process.exitCode=1;});
