import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import { Toaster } from "@/components/ui/sonner";
import { Toaster as BaseToaster } from "@/components/ui/toast";
import "./theme-overrides.css";
import { TooltipProvider } from "@/components/ui/tooltip";
document.documentElement.classList.add("light");
createRoot(document.getElementById("root")!).render(<React.StrictMode><TooltipProvider><App /><Toaster /><BaseToaster /></TooltipProvider></React.StrictMode>);
